// Real and accurate data of top Indian colleges
export const collegesData = [
  // IIT Colleges
  {
    name: 'Indian Institute of Technology Bombay',
    location: 'Mumbai, Maharashtra',
    state: 'Maharashtra',
    founded: 1958,
    ranking: 1,
    nirf_overall_rank: 3,
    nirf_engineering_rank: 1,
    fees: 237000,
    placement_rate: 98,
    rating: 4.8,
    description: 'IIT Bombay is one of the premier engineering institutions in India, known for research excellence and world-class faculty.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA'],
    reviews_count: 2450,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/IIT_Bombay_Logo.svg/200px-IIT_Bombay_Logo.svg.png',
    type: 'Government',
    cutoff_general: 94,
    cutoff_obc: 90,
    cutoff_sc: 82,
    total_seats: 1235,
    website: 'www.iitb.ac.in'
  },
  {
    name: 'Indian Institute of Technology Delhi',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1961,
    ranking: 2,
    nirf_overall_rank: 4,
    nirf_engineering_rank: 2,
    fees: 237000,
    placement_rate: 97,
    rating: 4.8,
    description: 'IIT Delhi is a premier engineering institute known for its rigorous academic programs and excellent placements.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 2200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/IIT_Delhi_Logo.png/200px-IIT_Delhi_Logo.png',
    type: 'Government',
    cutoff_general: 95,
    cutoff_obc: 91,
    cutoff_sc: 83,
    total_seats: 1166,
    website: 'www.iitd.ac.in'
  },
  {
    name: 'Indian Institute of Technology Madras',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1959,
    ranking: 3,
    nirf_overall_rank: 5,
    nirf_engineering_rank: 3,
    fees: 237000,
    placement_rate: 98,
    rating: 4.8,
    description: 'IIT Madras is renowned for its research contributions and has a strong entrepreneurial culture.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 2150,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/IIT_Madras_Logo.svg/200px-IIT_Madras_Logo.svg.png',
    type: 'Government',
    cutoff_general: 94,
    cutoff_obc: 90,
    cutoff_sc: 82,
    total_seats: 1180,
    website: 'www.iitm.ac.in'
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    location: 'Kanpur, Uttar Pradesh',
    state: 'Uttar Pradesh',
    founded: 1959,
    ranking: 4,
    nirf_overall_rank: 6,
    nirf_engineering_rank: 4,
    fees: 237000,
    placement_rate: 96,
    rating: 4.7,
    description: 'IIT Kanpur is known for its strong faculty and research programs with emphasis on innovation.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1800,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/IIT_Kanpur_Logo.svg/200px-IIT_Kanpur_Logo.svg.png',
    type: 'Government',
    cutoff_general: 93,
    cutoff_obc: 89,
    cutoff_sc: 81,
    total_seats: 1138,
    website: 'www.iitk.ac.in'
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    location: 'Kharagpur, West Bengal',
    state: 'West Bengal',
    founded: 1951,
    ranking: 5,
    nirf_overall_rank: 7,
    nirf_engineering_rank: 5,
    fees: 237000,
    placement_rate: 95,
    rating: 4.7,
    description: 'India\'s first IIT with a rich history and tradition of excellence in engineering education.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 2000,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/IIT_Kharagpur_Logo.svg/200px-IIT_Kharagpur_Logo.svg.png',
    type: 'Government',
    cutoff_general: 92,
    cutoff_obc: 88,
    cutoff_sc: 80,
    total_seats: 1342,
    website: 'www.iitkgp.ac.in'
  },
  {
    name: 'Indian Institute of Technology Roorkee',
    location: 'Roorkee, Uttarakhand',
    state: 'Uttarakhand',
    founded: 1854,
    ranking: 6,
    nirf_overall_rank: 17,
    nirf_engineering_rank: 6,
    fees: 237000,
    placement_rate: 94,
    rating: 4.6,
    description: 'One of India\'s oldest technical institutions with strong civil engineering legacy.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1600,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/IIT_Roorkee_Logo.svg/200px-IIT_Roorkee_Logo.svg.png',
    type: 'Government',
    cutoff_general: 90,
    cutoff_obc: 86,
    cutoff_sc: 78,
    total_seats: 810,
    website: 'www.iitr.ac.in'
  },
  {
    name: 'Indian Institute of Technology Guwahati',
    location: 'Guwahati, Assam',
    state: 'Assam',
    founded: 1994,
    ranking: 7,
    nirf_overall_rank: 19,
    nirf_engineering_rank: 7,
    fees: 237000,
    placement_rate: 93,
    rating: 4.6,
    description: 'A relatively new IIT focused on quality education and research in the Northeast region.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/IIT_Guwahati_Logo.svg/200px-IIT_Guwahati_Logo.svg.png',
    type: 'Government',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 650,
    website: 'www.iitg.ac.in'
  },
  {
    name: 'Indian Institute of Technology Hyderabad',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    founded: 2008,
    ranking: 8,
    nirf_overall_rank: 21,
    nirf_engineering_rank: 8,
    fees: 237000,
    placement_rate: 93,
    rating: 4.5,
    description: 'A modern IIT with state-of-the-art facilities and focus on interdisciplinary education.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 900,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/IIT_Hyderabad_logo.svg/200px-IIT_Hyderabad_logo.svg.png',
    type: 'Government',
    cutoff_general: 82,
    cutoff_obc: 78,
    cutoff_sc: 70,
    total_seats: 560,
    website: 'www.iith.ac.in'
  },
  {
    name: 'Indian Institute of Technology Indore',
    location: 'Indore, Madhya Pradesh',
    state: 'Madhya Pradesh',
    founded: 2009,
    ranking: 9,
    nirf_overall_rank: 38,
    nirf_engineering_rank: 9,
    fees: 237000,
    placement_rate: 92,
    rating: 4.5,
    description: 'Located in the heart of central India with modern infrastructure and growing reputation.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MSc'],
    reviews_count: 700,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Iit-indore-new-logo.svg/200px-Iit-indore-new-logo.svg.png',
    type: 'Government',
    cutoff_general: 80,
    cutoff_obc: 76,
    cutoff_sc: 68,
    total_seats: 450,
    website: 'www.iiti.ac.in'
  },
  {
    name: 'Indian Institute of Technology Bhubaneswar',
    location: 'Bhubaneswar, Odisha',
    state: 'Odisha',
    founded: 2008,
    ranking: 10,
    nirf_overall_rank: 40,
    nirf_engineering_rank: 10,
    fees: 237000,
    placement_rate: 92,
    rating: 4.5,
    description: 'A new generation IIT with focus on quality research and student development.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MSc'],
    reviews_count: 800,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/IIT_Bhubaneswar_Logo.svg/200px-IIT_Bhubaneswar_Logo.svg.png',
    type: 'Government',
    cutoff_general: 80,
    cutoff_obc: 76,
    cutoff_sc: 68,
    total_seats: 490,
    website: 'www.iitbbs.ac.in'
  },

  // NIT Colleges
  {
    name: 'National Institute of Technology Trichy',
    location: 'Tiruchirappalli, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1964,
    ranking: 11,
    nirf_overall_rank: 28,
    nirf_engineering_rank: 11,
    fees: 165000,
    placement_rate: 95,
    rating: 4.7,
    description: 'One of the oldest and most respected NITs with excellent placement record.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1800,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/NIT_Trichy_Logo.svg/200px-NIT_Trichy_Logo.svg.png',
    type: 'Government',
    cutoff_general: 87,
    cutoff_obc: 83,
    cutoff_sc: 75,
    total_seats: 1080,
    website: 'www.nitt.edu'
  },
  {
    name: 'National Institute of Technology Surathkal',
    location: 'Surathkal, Karnataka',
    state: 'Karnataka',
    founded: 1960,
    ranking: 12,
    nirf_overall_rank: 29,
    nirf_engineering_rank: 12,
    fees: 165000,
    placement_rate: 94,
    rating: 4.6,
    description: 'Located on the coast with excellent infrastructure and strong academics.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1500,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/National_Institute_of_Technology_Surathkal_logo.svg/200px-National_Institute_of_Technology_Surathkal_logo.svg.png',
    type: 'Government',
    cutoff_general: 86,
    cutoff_obc: 82,
    cutoff_sc: 74,
    total_seats: 960,
    website: 'www.nitk.ac.in'
  },
  {
    name: 'National Institute of Technology Warangal',
    location: 'Warangal, Telangana',
    state: 'Telangana',
    founded: 1959,
    ranking: 13,
    nirf_overall_rank: 30,
    nirf_engineering_rank: 13,
    fees: 165000,
    placement_rate: 93,
    rating: 4.6,
    description: 'A leading NIT in South India with strong campus placement records.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/NIT_Warangal_Logo.svg/200px-NIT_Warangal_Logo.svg.png',
    type: 'Government',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 900,
    website: 'www.nitw.ac.in'
  },
  {
    name: 'National Institute of Technology Rourkela',
    location: 'Rourkela, Odisha',
    state: 'Odisha',
    founded: 1961,
    ranking: 14,
    nirf_overall_rank: 31,
    nirf_engineering_rank: 14,
    fees: 165000,
    placement_rate: 92,
    rating: 4.5,
    description: 'A premier NIT with strong metallurgical engineering background.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1300,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/National_Institute_of_Technology_Rourkela.svg/200px-National_Institute_of_Technology_Rourkela.svg.png',
    type: 'Government',
    cutoff_general: 84,
    cutoff_obc: 80,
    cutoff_sc: 72,
    total_seats: 900,
    website: 'www.nit.rourkela.ac.in'
  },
  {
    name: 'National Institute of Technology Durgapur',
    location: 'Durgapur, West Bengal',
    state: 'West Bengal',
    founded: 1960,
    ranking: 15,
    nirf_overall_rank: 36,
    nirf_engineering_rank: 15,
    fees: 165000,
    placement_rate: 91,
    rating: 4.5,
    description: 'A well-established NIT in Eastern India with good industry connections.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1100,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/NIT_Durgapur_logo.svg/200px-NIT_Durgapur_logo.svg.png',
    type: 'Government',
    cutoff_general: 83,
    cutoff_obc: 79,
    cutoff_sc: 71,
    total_seats: 840,
    website: 'www.nitdgp.ac.in'
  },
  {
    name: 'National Institute of Technology Allahabad',
    location: 'Prayagraj, Uttar Pradesh',
    state: 'Uttar Pradesh',
    founded: 1964,
    ranking: 16,
    nirf_overall_rank: 37,
    nirf_engineering_rank: 16,
    fees: 165000,
    placement_rate: 90,
    rating: 4.5,
    description: 'One of the oldest NITs with strong academic heritage.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/NIT_Allahabad_Logo.png/200px-NIT_Allahabad_Logo.png',
    type: 'Government',
    cutoff_general: 82,
    cutoff_obc: 78,
    cutoff_sc: 70,
    total_seats: 800,
    website: 'www.nita.ac.in'
  },
  {
    name: 'National Institute of Technology Calicut',
    location: 'Calicut, Kerala',
    state: 'Kerala',
    founded: 1966,
    ranking: 17,
    nirf_overall_rank: 43,
    nirf_engineering_rank: 17,
    fees: 165000,
    placement_rate: 89,
    rating: 4.4,
    description: 'A premier technical institute in Kerala with excellent research facilities.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1000,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/NIT_Calicut_logo.svg/200px-NIT_Calicut_logo.svg.png',
    type: 'Government',
    cutoff_general: 81,
    cutoff_obc: 77,
    cutoff_sc: 69,
    total_seats: 750,
    website: 'www.nitc.ac.in'
  },
  {
    name: 'National Institute of Technology Jaipur',
    location: 'Jaipur, Rajasthan',
    state: 'Rajasthan',
    founded: 2007,
    ranking: 18,
    nirf_overall_rank: 48,
    nirf_engineering_rank: 18,
    fees: 165000,
    placement_rate: 88,
    rating: 4.4,
    description: 'A growing NIT with modern facilities and good placement opportunities.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 850,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/NIT_Jaipur_Logo.svg/200px-NIT_Jaipur_Logo.svg.png',
    type: 'Government',
    cutoff_general: 79,
    cutoff_obc: 75,
    cutoff_sc: 67,
    total_seats: 650,
    website: 'www.nitjaipur.ac.in'
  },

  // BITS Pilani
  {
    name: 'BITS Pilani (Pilani Campus)',
    location: 'Pilani, Rajasthan',
    state: 'Rajasthan',
    founded: 1972,
    ranking: 19,
    nirf_overall_rank: 11,
    nirf_engineering_rank: 19,
    fees: 2500000,
    placement_rate: 96,
    rating: 4.7,
    description: 'A private institute with high academic standards and excellent placements.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1600,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/BITS_Pilani-Logo.svg/200px-BITS_Pilani-Logo.svg.png',
    type: 'Private',
    cutoff_general: 88,
    cutoff_obc: 84,
    cutoff_sc: 76,
    total_seats: 850,
    website: 'www.bits-pilani.ac.in'
  },
  {
    name: 'BITS Pilani (Hyderabad Campus)',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    founded: 2008,
    ranking: 20,
    nirf_overall_rank: 22,
    nirf_engineering_rank: 20,
    fees: 2500000,
    placement_rate: 95,
    rating: 4.6,
    description: 'BITS Hyderabad offers excellent infrastructure and placement opportunities.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/BITS_Pilani-Logo.svg/200px-BITS_Pilani-Logo.svg.png',
    type: 'Private',
    cutoff_general: 86,
    cutoff_obc: 82,
    cutoff_sc: 74,
    total_seats: 700,
    website: 'www.bits-pilani.ac.in/hyderabad'
  },
  {
    name: 'BITS Pilani (Goa Campus)',
    location: 'Goa, Goa',
    state: 'Goa',
    founded: 2004,
    ranking: 21,
    nirf_overall_rank: 23,
    nirf_engineering_rank: 21,
    fees: 2500000,
    placement_rate: 94,
    rating: 4.6,
    description: 'BITS Goa is known for its scenic campus and quality education.',
    courses: ['B.Tech', 'M.Tech', 'PhD', 'MBA', 'MSc'],
    reviews_count: 1000,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/BITS_Pilani-Logo.svg/200px-BITS_Pilani-Logo.svg.png',
    type: 'Private',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 600,
    website: 'www.bits-pilani.ac.in/goa'
  },

  // Delhi University Colleges
  {
    name: 'Delhi University - St. Stephens College',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1881,
    ranking: 22,
    nirf_overall_rank: 14,
    nirf_engineering_rank: 50,
    fees: 350000,
    placement_rate: 85,
    rating: 4.5,
    description: 'One of India\'s premier undergraduate colleges with a long history of excellence.',
    courses: ['BA', 'BSc', 'BCom', 'BCA'],
    reviews_count: 1800,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/St._Stephens_College_Delhi_Logo.svg/200px-St._Stephens_College_Delhi_Logo.svg.png',
    type: 'Government',
    cutoff_general: 92,
    cutoff_obc: 88,
    cutoff_sc: 80,
    total_seats: 600,
    website: 'www.ststephens.edu'
  },
  {
    name: 'Delhi University - Miranda House',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1948,
    ranking: 23,
    nirf_overall_rank: 15,
    nirf_engineering_rank: 50,
    fees: 350000,
    placement_rate: 84,
    rating: 4.5,
    description: 'A leading women\'s college with excellent academic record.',
    courses: ['BA', 'BSc', 'BCom'],
    reviews_count: 1500,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Miranda_House_logo.svg/200px-Miranda_House_logo.svg.png',
    type: 'Government',
    cutoff_general: 94,
    cutoff_obc: 90,
    cutoff_sc: 82,
    total_seats: 500,
    website: 'www.mirandahouse.ac.in'
  },
  {
    name: 'Delhi University - Delhi College of Arts and Commerce',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1792,
    ranking: 24,
    nirf_overall_rank: 16,
    nirf_engineering_rank: 50,
    fees: 350000,
    placement_rate: 83,
    rating: 4.4,
    description: 'One of the oldest colleges in India with rich academic traditions.',
    courses: ['BA', 'BCom', 'BCA'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Delhi_University_Logo.png/200px-Delhi_University_Logo.png',
    type: 'Government',
    cutoff_general: 90,
    cutoff_obc: 86,
    cutoff_sc: 78,
    total_seats: 700,
    website: 'www.delhicollegeofarts.ac.in'
  },
  {
    name: 'Delhi University - Ramjas College',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1945,
    ranking: 25,
    nirf_overall_rank: 20,
    nirf_engineering_rank: 50,
    fees: 350000,
    placement_rate: 82,
    rating: 4.4,
    description: 'A reputed college with strong faculty and good placement support.',
    courses: ['BA', 'BSc', 'BCom', 'BCA'],
    reviews_count: 1200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Ramjas_College_Logo.png/200px-Ramjas_College_Logo.png',
    type: 'Government',
    cutoff_general: 89,
    cutoff_obc: 85,
    cutoff_sc: 77,
    total_seats: 650,
    website: 'www.ramjas.ac.in'
  },
  {
    name: 'Delhi University - Shaheed Bhagat Singh College',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1920,
    ranking: 26,
    nirf_overall_rank: 24,
    nirf_engineering_rank: 50,
    fees: 350000,
    placement_rate: 81,
    rating: 4.4,
    description: 'A historic college known for academic excellence and social responsibility.',
    courses: ['BA', 'BSc', 'BCom', 'BCA'],
    reviews_count: 1100,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Delhi_University_Logo.png/200px-Delhi_University_Logo.png',
    type: 'Government',
    cutoff_general: 88,
    cutoff_obc: 84,
    cutoff_sc: 76,
    total_seats: 600,
    website: 'www.sbscollege.ac.in'
  },

  // Top Private Universities
  {
    name: 'Manipal Academy of Higher Education (MAHE)',
    location: 'Manipal, Karnataka',
    state: 'Karnataka',
    founded: 1953,
    ranking: 27,
    nirf_overall_rank: 32,
    nirf_engineering_rank: 22,
    fees: 1800000,
    placement_rate: 93,
    rating: 4.6,
    description: 'A prestigious deemed university with excellent infrastructure and global recognition.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Manipal_Academy_of_Higher_Education_Logo.svg/200px-Manipal_Academy_of_Higher_Education_Logo.svg.png',
    type: 'Private',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 1200,
    website: 'www.manipal.edu'
  },
  {
    name: 'VIT University (Vellore)',
    location: 'Vellore, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1984,
    ranking: 28,
    nirf_overall_rank: 35,
    nirf_engineering_rank: 23,
    fees: 1600000,
    placement_rate: 92,
    rating: 4.5,
    description: 'A leading engineering university with strong industry connections.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc'],
    reviews_count: 1300,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/VIT_University_Logo.svg/200px-VIT_University_Logo.svg.png',
    type: 'Private',
    cutoff_general: 83,
    cutoff_obc: 79,
    cutoff_sc: 71,
    total_seats: 1400,
    website: 'www.vit.ac.in'
  },
  {
    name: 'Lovely Professional University (LPU)',
    location: 'Phagwara, Punjab',
    state: 'Punjab',
    founded: 2005,
    ranking: 29,
    nirf_overall_rank: 44,
    nirf_engineering_rank: 24,
    fees: 1200000,
    placement_rate: 91,
    rating: 4.4,
    description: 'A rapidly growing university with modern facilities and good placements.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc'],
    reviews_count: 1100,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/LPU_logo.svg/200px-LPU_logo.svg.png',
    type: 'Private',
    cutoff_general: 75,
    cutoff_obc: 71,
    cutoff_sc: 63,
    total_seats: 2000,
    website: 'www.lpu.in'
  },
  {
    name: 'Shiv Nadar University',
    location: 'Greater Noida, Uttar Pradesh',
    state: 'Uttar Pradesh',
    founded: 2009,
    ranking: 30,
    nirf_overall_rank: 25,
    nirf_engineering_rank: 26,
    fees: 1500000,
    placement_rate: 90,
    rating: 4.5,
    description: 'A premium private university with excellent faculty and research opportunities.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc'],
    reviews_count: 950,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Shiv_Nadar_University_Logo.svg/200px-Shiv_Nadar_University_Logo.svg.png',
    type: 'Private',
    cutoff_general: 84,
    cutoff_obc: 80,
    cutoff_sc: 72,
    total_seats: 900,
    website: 'www.snu.edu.in'
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    location: 'Coimbatore, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1994,
    ranking: 31,
    nirf_overall_rank: 45,
    nirf_engineering_rank: 27,
    fees: 1400000,
    placement_rate: 89,
    rating: 4.4,
    description: 'A values-based private university with strong engineering programs.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc'],
    reviews_count: 1000,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Amrita_Vishwa_Vidyapeetham_logo.svg/200px-Amrita_Vishwa_Vidyapeetham_logo.svg.png',
    type: 'Private',
    cutoff_general: 80,
    cutoff_obc: 76,
    cutoff_sc: 68,
    total_seats: 950,
    website: 'www.amrita.edu'
  },
  {
    name: 'Chandigarh University',
    location: 'Mohali, Punjab',
    state: 'Punjab',
    founded: 2012,
    ranking: 32,
    nirf_overall_rank: 51,
    nirf_engineering_rank: 28,
    fees: 1100000,
    placement_rate: 88,
    rating: 4.3,
    description: 'A modern university with focus on innovation and entrepreneurship.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BCA', 'MSc', 'BA', 'BCom'],
    reviews_count: 900,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Chandigarh_University_Logo.svg/200px-Chandigarh_University_Logo.svg.png',
    type: 'Private',
    cutoff_general: 78,
    cutoff_obc: 74,
    cutoff_sc: 66,
    total_seats: 1500,
    website: 'www.cuchd.in'
  },
  {
    name: 'Ashoka University',
    location: 'Sonipat, Haryana',
    state: 'Haryana',
    founded: 2014,
    ranking: 33,
    nirf_overall_rank: 18,
    nirf_engineering_rank: 50,
    fees: 2000000,
    placement_rate: 92,
    rating: 4.6,
    description: 'A premium liberal arts and sciences university with highly selective admissions.',
    courses: ['BA', 'BSc', 'BCom', 'MA', 'MSc', 'MBA'],
    reviews_count: 800,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Ashoka_University_Logo.svg/200px-Ashoka_University_Logo.svg.png',
    type: 'Private',
    cutoff_general: 96,
    cutoff_obc: 92,
    cutoff_sc: 84,
    total_seats: 400,
    website: 'www.ashoka.edu.in'
  },

  // State Universities
  {
    name: 'University of Calcutta',
    location: 'Kolkata, West Bengal',
    state: 'West Bengal',
    founded: 1857,
    ranking: 34,
    nirf_overall_rank: 50,
    nirf_engineering_rank: 50,
    fees: 180000,
    placement_rate: 75,
    rating: 4.2,
    description: 'India\'s oldest university with strong arts and sciences programs.',
    courses: ['BA', 'BSc', 'BCom', 'MA', 'MSc', 'MBA'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/University_of_Calcutta_logo.svg/200px-University_of_Calcutta_logo.svg.png',
    type: 'Government',
    cutoff_general: 75,
    cutoff_obc: 71,
    cutoff_sc: 63,
    total_seats: 2000,
    website: 'www.caluniv.ac.in'
  },
  {
    name: 'Banaras Hindu University (BHU)',
    location: 'Varanasi, Uttar Pradesh',
    state: 'Uttar Pradesh',
    founded: 1916,
    ranking: 35,
    nirf_overall_rank: 26,
    nirf_engineering_rank: 34,
    fees: 250000,
    placement_rate: 82,
    rating: 4.4,
    description: 'A central university with diverse programs and strong cultural heritage.',
    courses: ['BA', 'BSc', 'BCom', 'B.Tech', 'MA', 'MSc', 'MBA'],
    reviews_count: 1600,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Banaras_Hindu_University.svg/200px-Banaras_Hindu_University.svg.png',
    type: 'Government',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 2200,
    website: 'www.bhu.ac.in'
  },
  {
    name: 'University of Delhi (General)',
    location: 'Delhi, Delhi',
    state: 'Delhi',
    founded: 1922,
    ranking: 36,
    nirf_overall_rank: 22,
    nirf_engineering_rank: 50,
    fees: 200000,
    placement_rate: 78,
    rating: 4.2,
    description: 'Delhi University is one of India\'s premier universities with multiple affiliated colleges.',
    courses: ['BA', 'BSc', 'BCom', 'BCA', 'MA', 'MSc', 'MBA'],
    reviews_count: 2000,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Delhi_University_Logo.png/200px-Delhi_University_Logo.png',
    type: 'Government',
    cutoff_general: 88,
    cutoff_obc: 84,
    cutoff_sc: 76,
    total_seats: 3000,
    website: 'www.du.ac.in'
  },
  {
    name: 'Jawaharlal Nehru University (JNU)',
    location: 'New Delhi, Delhi',
    state: 'Delhi',
    founded: 1969,
    ranking: 37,
    nirf_overall_rank: 9,
    nirf_engineering_rank: 50,
    fees: 180000,
    placement_rate: 72,
    rating: 4.1,
    description: 'A central university known for research and social sciences.',
    courses: ['BA', 'BSc', 'MA', 'MSc', 'M.Phil', 'PhD'],
    reviews_count: 1200,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/JNU_logo.svg/200px-JNU_logo.svg.png',
    type: 'Government',
    cutoff_general: 80,
    cutoff_obc: 76,
    cutoff_sc: 68,
    total_seats: 1500,
    website: 'www.jnu.ac.in'
  },
  {
    name: 'Pune University',
    location: 'Pune, Maharashtra',
    state: 'Maharashtra',
    founded: 1949,
    ranking: 38,
    nirf_overall_rank: 46,
    nirf_engineering_rank: 50,
    fees: 200000,
    placement_rate: 76,
    rating: 4.1,
    description: 'A major university in Western India with diverse programs.',
    courses: ['BA', 'BSc', 'BCom', 'B.Tech', 'MA', 'MSc', 'MBA'],
    reviews_count: 1300,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Savitribai_Phule_Pune_University_logo.svg/200px-Savitribai_Phule_Pune_University_logo.svg.png',
    type: 'Government',
    cutoff_general: 78,
    cutoff_obc: 74,
    cutoff_sc: 66,
    total_seats: 2500,
    website: 'www.unipune.ac.in'
  },
  {
    name: 'University of Hyderabad',
    location: 'Hyderabad, Telangana',
    state: 'Telangana',
    founded: 1974,
    ranking: 39,
    nirf_overall_rank: 33,
    nirf_engineering_rank: 50,
    fees: 200000,
    placement_rate: 75,
    rating: 4.1,
    description: 'A central university focusing on research and higher education.',
    courses: ['BA', 'BSc', 'MA', 'MSc', 'M.Phil', 'PhD'],
    reviews_count: 1100,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/University_of_Hyderabad_Logo.svg/200px-University_of_Hyderabad_Logo.svg.png',
    type: 'Government',
    cutoff_general: 76,
    cutoff_obc: 72,
    cutoff_sc: 64,
    total_seats: 1200,
    website: 'www.uohyd.ac.in'
  },
  {
    name: 'Anna University (CEG Campus)',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1794,
    ranking: 40,
    nirf_overall_rank: 20,
    nirf_engineering_rank: 20,
    fees: 80000,
    placement_rate: 85,
    rating: 4.4,
    description: 'A top state public university in Tamil Nadu with a legacy engineering campus and strong academic reputation.',
    courses: ['B.E./B.Tech', 'M.E./M.Tech', 'MBA', 'MCA', 'PhD'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Anna_University_Logo.svg',
    type: 'Government',
    cutoff_general: 90,
    cutoff_obc: 86,
    cutoff_sc: 78,
    total_seats: 1400,
    website: 'www.annauniv.edu'
  },
  {
    name: 'SRM Institute of Science and Technology',
    location: 'Kattankulathur, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1985,
    ranking: 41,
    nirf_overall_rank: 14,
    nirf_engineering_rank: 14,
    fees: 400000,
    placement_rate: 90,
    rating: 4.3,
    description: 'A large private university near Chennai known for engineering, infrastructure, and strong industry links.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MCA', 'PhD'],
    reviews_count: 1600,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/6/6a/SRM_Institute_of_Science_and_Technology_logo.png',
    type: 'Private',
    cutoff_general: 78,
    cutoff_obc: 74,
    cutoff_sc: 66,
    total_seats: 2200,
    website: 'www.srmist.edu.in'
  },
  {
    name: 'SSN College of Engineering',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1996,
    ranking: 42,
    nirf_overall_rank: 82,
    nirf_engineering_rank: 47,
    fees: 200000,
    placement_rate: 88,
    rating: 4.3,
    description: 'A reputed engineering college known for academic rigor, strong placements, and industry-relevant programs.',
    courses: ['B.E./B.Tech', 'M.E./M.Tech', 'MBA', 'PhD'],
    reviews_count: 900,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/2/23/SSN_College_of_Engineering_logo.png',
    type: 'Private',
    cutoff_general: 82,
    cutoff_obc: 78,
    cutoff_sc: 70,
    total_seats: 1200,
    website: 'www.ssn.edu.in'
  },
  {
    name: 'Madras Institute of Technology (Anna University)',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1949,
    ranking: 43,
    nirf_overall_rank: 20,
    nirf_engineering_rank: 20,
    fees: 90000,
    placement_rate: 86,
    rating: 4.3,
    description: 'A historic engineering campus under Anna University, known for aerospace, electronics, and strong technical programs.',
    courses: ['B.E./B.Tech', 'M.E./M.Tech', 'MCA', 'PhD'],
    reviews_count: 850,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Anna_University_Logo.svg',
    type: 'Government',
    cutoff_general: 88,
    cutoff_obc: 84,
    cutoff_sc: 76,
    total_seats: 1000,
    website: 'www.annauniv.edu'
  },
  {
    name: 'Rajalakshmi Engineering College',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1997,
    ranking: 44,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 86,
    fees: 185000,
    placement_rate: 84,
    rating: 4.2,
    description: 'A reputed autonomous engineering college in Chennai with good placements and strong industry-oriented programs.',
    courses: ['B.E./B.Tech', 'M.E./M.Tech', 'MBA', 'PhD'],
    reviews_count: 760,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Anna_University_Logo.svg',
    type: 'Private',
    cutoff_general: 80,
    cutoff_obc: 76,
    cutoff_sc: 68,
    total_seats: 1800,
    website: 'www.rajalakshmi.org'
  },
  {
    name: 'Sri Sairam Engineering College',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1995,
    ranking: 45,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 100,
    fees: 170000,
    placement_rate: 83,
    rating: 4.2,
    description: 'A well-known Chennai engineering institution with consistent placements and broad undergraduate intake.',
    courses: ['B.E./B.Tech', 'M.E./M.Tech', 'MBA'],
    reviews_count: 700,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Anna_University_Logo.svg',
    type: 'Private',
    cutoff_general: 78,
    cutoff_obc: 74,
    cutoff_sc: 66,
    total_seats: 2100,
    website: 'www.sairam.edu.in'
  },
  {
    name: 'Sathyabama Institute of Science and Technology',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1987,
    ranking: 46,
    nirf_overall_rank: 51,
    nirf_engineering_rank: 66,
    fees: 250000,
    placement_rate: 85,
    rating: 4.2,
    description: 'A Chennai-based deemed university offering engineering and allied programs with strong campus infrastructure.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'B.Arch', 'PhD'],
    reviews_count: 980,
    image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1d/Anna_University_Logo.svg',
    type: 'Private',
    cutoff_general: 76,
    cutoff_obc: 72,
    cutoff_sc: 64,
    total_seats: 2400,
    website: 'www.sathyabama.ac.in'
  },
  {
    name: 'Loyola College, Chennai',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1925,
    ranking: 47,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 100,
    fees: 120000,
    placement_rate: 78,
    rating: 4.2,
    description: 'A highly reputed autonomous arts and science college in Chennai with strong academic and placement outcomes.',
    courses: ['BA', 'BSc', 'BCom', 'BCA', 'MA', 'MSc', 'MCom'],
    reviews_count: 1400,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Loyola_College_Chennai_Logo.png/200px-Loyola_College_Chennai_Logo.png',
    type: 'Private',
    cutoff_general: 85,
    cutoff_obc: 81,
    cutoff_sc: 73,
    total_seats: 2600,
    website: 'www.loyolacollege.edu'
  },
  {
    name: 'Hindustan Institute of Technology and Science',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 1985,
    ranking: 48,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 150,
    fees: 260000,
    placement_rate: 80,
    rating: 4.1,
    description: 'A Chennai-based deemed university known for engineering, aeronautical programs, and multidisciplinary courses.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BBA', 'PhD'],
    reviews_count: 820,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Anna_University_Logo.svg/200px-Anna_University_Logo.svg.png',
    type: 'Private',
    cutoff_general: 74,
    cutoff_obc: 70,
    cutoff_sc: 62,
    total_seats: 2000,
    website: 'www.hindustanuniv.ac.in'
  },
  {
    name: 'Amity University Chennai',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 2009,
    ranking: 49,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 150,
    fees: 275000,
    placement_rate: 78,
    rating: 4.0,
    description: 'A private university campus in Chennai offering engineering, management, and science programs with modern infrastructure.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'BSc', 'BBA'],
    reviews_count: 600,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Amity_University_logo.svg/200px-Amity_University_logo.svg.png',
    type: 'Private',
    cutoff_general: 72,
    cutoff_obc: 68,
    cutoff_sc: 60,
    total_seats: 1500,
    website: 'www.amity.edu/chennai'
  },
  {
    name: 'Amrita Vishwa Vidyapeetham (Chennai Campus)',
    location: 'Chennai, Tamil Nadu',
    state: 'Tamil Nadu',
    founded: 2019,
    ranking: 50,
    nirf_overall_rank: 100,
    nirf_engineering_rank: 150,
    fees: 300000,
    placement_rate: 82,
    rating: 4.1,
    description: 'Amrita Chennai campus with emerging engineering and interdisciplinary programs under Amrita Vishwa Vidyapeetham.',
    courses: ['B.Tech', 'M.Tech', 'MBA', 'PhD'],
    reviews_count: 420,
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Amrita_Vishwa_Vidyapeetham_logo.svg/200px-Amrita_Vishwa_Vidyapeetham_logo.svg.png',
    type: 'Private',
    cutoff_general: 75,
    cutoff_obc: 71,
    cutoff_sc: 63,
    total_seats: 900,
    website: 'www.amrita.edu/campus/chennai'
  },
];
